from typing import Iterator, Optional, Protocol, Tuple


class ObjectStorage(Protocol):
    @property
    def bucket_name(self) -> str: ...

    def public_url(self, key: str) -> str: ...

    def upload(self, data, object_name: str, content_type: Optional[str] = None) -> None: ...

    def download(self, path: str, object_name: str) -> None: ...

    def delete_object(self, key: str) -> None: ...

    def delete_prefix(self, prefix: str) -> None: ...

    def stream_object(
        self, object_name: str, chunk_size: int = 1024 * 1024
    ) -> Tuple[Iterator[bytes], str, Optional[int]]: ...

    def generate_presigned_upload_url(
        self,
        object_name: str,
        expiration: int = 3600,
        content_type: Optional[str] = None,
    ) -> str: ...

    def exists(self, object_name: str) -> bool: ...

    def copy(self, source_key: str, dest_key: str) -> None: ...

    def ensure_bucket(self) -> None: ...

    def set_public_read_policy(self) -> None: ...
