from __future__ import annotations

from typing import Protocol

from app.domain.entities import (
    District,
    Inference,
    Locality,
    Province,
    Road,
    Task,
    TaskStatus,
    TaskStatusHistory,
    User,
    Video,
)


class UserRepository(Protocol):
    def get(self, user_id: int) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def get_by_username_or_email(self, username: str, email: str) -> User | None: ...
    def find_by_identifier(self, identifier: str) -> User | None: ...
    def list_all(self, **filters) -> list[User]: ...
    def add(self, user: User) -> User: ...
    def delete(self, user: User) -> None: ...


class ProvinceRepository(Protocol):
    def list_all(self, **filters) -> list[Province]: ...


class DistrictRepository(Protocol):
    def list_all(self, **filters) -> list[District]: ...


class LocalityRepository(Protocol):
    def get(self, locality_id: int) -> Locality | None: ...
    def list_all(self) -> list[Locality]: ...
    def list_by_district(self, district_id: int) -> list[Locality]: ...


class VideoRepository(Protocol):
    def add(self, video: Video) -> Video: ...
    def delete(self, video: Video) -> None: ...


class TaskRepository(Protocol):
    def get(self, task_id: int) -> Task | None: ...
    def list_active(self) -> list[Task]: ...
    def list_archived(self) -> list[Task]: ...
    def list_by_status(self, status_id: str) -> list[Task]: ...
    def add(self, task: Task) -> Task: ...
    def delete_cascade(self, task: Task) -> None: ...


class TaskStatusRepository(Protocol):
    def get(self, status_id: str) -> TaskStatus | None: ...


class StatusHistoryRepository(Protocol):
    def get_current(self, task_id: int) -> TaskStatusHistory | None: ...
    def previous_non_archived(self, task_id: int, archived_id: str) -> TaskStatusHistory | None: ...
    def add(self, history: TaskStatusHistory) -> TaskStatusHistory: ...
    def delete_for_task(self, task_id: int) -> None: ...


class RoadRepository(Protocol):
    def list_by_video(self, video_id: int) -> list[Road]: ...
    def add(self, road: Road) -> Road: ...
    def delete(self, road: Road) -> None: ...
    def delete_for_video(self, video_id: int) -> None: ...


class InferenceRepository(Protocol):
    def add(self, inference: Inference) -> Inference: ...
    def delete(self, inference: Inference) -> None: ...


class UnitOfWork(Protocol):
    users: UserRepository
    provinces: ProvinceRepository
    districts: DistrictRepository
    localities: LocalityRepository
    videos: VideoRepository
    tasks: TaskRepository
    task_statuses: TaskStatusRepository
    status_histories: StatusHistoryRepository
    roads: RoadRepository
    inferences: InferenceRepository

    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def flush(self) -> None: ...
    def refresh(self, entity) -> None: ...
    def expire_all(self) -> None: ...
