"""urls de resultados de inferencia ahora JSON, agregado campo para determinados

Revision ID: 1e347a97f43e
Revises: 29503b4a9aca
Create Date: 2025-08-15 16:06:57.353352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e347a97f43e'
down_revision: Union[str, None] = '29503b4a9aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference', sa.Column('transition_counts', sa.JSON(), nullable=False))
    op.add_column('inference', sa.Column('transition_undetermined', sa.JSON(), nullable=False))
    op.add_column('inference', sa.Column('transition_determined', sa.JSON(), nullable=False))
    op.alter_column('inference', 'url_video_processed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('inference', 'url_transition_counts')
    op.drop_column('inference', 'url_transition_undetermined')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference', sa.Column('url_transition_undetermined', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('inference', sa.Column('url_transition_counts', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('inference', 'url_video_processed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('inference', 'transition_determined')
    op.drop_column('inference', 'transition_undetermined')
    op.drop_column('inference', 'transition_counts')
    # ### end Alembic commands ###
