"""Road.polygon to json

Revision ID: 29503b4a9aca
Revises: 20250809_02
Create Date: 2025-08-15 13:39:36.077795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29503b4a9aca'
down_revision: Union[str, None] = '20250809_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually convert TEXT to JSON using USING clause
    op.execute("ALTER TABLE road ALTER COLUMN polygon TYPE JSON USING polygon::json")
    
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('road', 'polygon',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
