"""Delete route fkey

Revision ID: 4d21838783f9
Revises: 866bbc1ccf81
Create Date: 2025-07-09 17:17:58.028030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d21838783f9'
down_revision: Union[str, None] = '866bbc1ccf81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('road_route_id_fkey'), 'road', type_='foreignkey')
    op.drop_column('road', 'route_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road', sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('road_route_id_fkey'), 'road', 'route', ['route_id'], ['id'])
    # ### end Alembic commands ###
