"""date to task

Revision ID: 4d31e8d8d9ca
Revises: bf69e36fa4fd
Create Date: 2025-07-19 12:16:42.294241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d31e8d8d9ca'
down_revision: Union[str, None] = 'bf69e36fa4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('task', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('task', 'created_at')
    op.drop_column('task', 'date')
    # ### end Alembic commands ###
