"""quitado

Revision ID: 68648c7d6c08
Revises: 597200f3f1a9
Create Date: 2025-08-16 12:33:26.733445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68648c7d6c08'
down_revision: Union[str, None] = '597200f3f1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inference', 'url_video_processed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inference', 'url_video_processed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
