"""Agregado url_data_obj_history al Inference

Revision ID: e9c274f8934e
Revises: 68648c7d6c08
Create Date: 2025-08-19 14:28:52.019512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e9c274f8934e'
down_revision: Union[str, None] = '68648c7d6c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference', sa.Column('url_data_obj_history', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inference', 'url_data_obj_history')
    # ### end Alembic commands ###
