"""eliminado campo number de road

Revision ID: 597200f3f1a9
Revises: 1e347a97f43e
Create Date: 2025-08-15 17:34:14.567300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '597200f3f1a9'
down_revision: Union[str, None] = '1e347a97f43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('road', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
