"""Create table Inference

Revision ID: 866bbc1ccf81
Revises: 7f5368296c74
Create Date: 2025-07-09 12:53:20.450662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '866bbc1ccf81'
down_revision: Union[str, None] = '7f5368296c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('url_transition_counts', sa.String(), nullable=False),
    sa.Column('url_transition_undetermined', sa.String(), nullable=False),
    sa.Column('url_video_processed', sa.String(), nullable=False),
    sa.Column('inferred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference')
    # ### end Alembic commands ###
